services:
  egl:
    container_name: egl
    hostname: egl
    # Change tag `latest` to Ubuntu versions such as `24.04`, use a persistent tag such as `24.04-20210101010101` to persist a certain container version
    image: ghcr.io/aer1s/nvidia-egl-desktop:latest
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tmpfs:
      - "/dev/shm:rw"
    #    volumes:
    #    - 'egl-cache-vol:/cache'
    #    - 'egl-root-vol:/home/ubuntu'
    # Uncomment the below line to disable network isolation for WebRTC connectivity, display `:20` and `:21` should not be used in the host, may show an error if disallowed by the cluster
    #    network_mode: 'host'
    environment:
      - TZ=UTC
      - DISPLAY_SIZEW=1920
      - DISPLAY_SIZEH=1080
      - DISPLAY_REFRESH=60
      - DISPLAY_DPI=96
      - DISPLAY_CDEPTH=24
      # Keep to default unless you know what you are doing with VirtualGL, `VGL_DISPLAY` should be set to either `egl[n]` or `/dev/dri/card[n]` only when the device was passed to the container
      #    - VGL_DISPLAY=egl
      # User password of container
      - PASSWD=mypasswd
      # Uncomment to enable KasmVNC instead of Selkies, `SELKIES_BASIC_AUTH_PASSWORD` is used for authentication with KasmVNC, defaulting to `PASSWD` if not provided
      # Uses: `SELKIES_ENABLE_BASIC_AUTH`, `SELKIES_BASIC_AUTH_USER`, `SELKIES_BASIC_AUTH_PASSWORD`, `SELKIES_ENABLE_RESIZE`, `SELKIES_ENABLE_HTTPS`, `SELKIES_HTTPS_CERT`, `SELKIES_HTTPS_KEY`
      #    - KASMVNC_ENABLE=true
      # Number of threads for encoding frames with KasmVNC, default value is all threads
      #    - name: KASMVNC_THREADS=0
      ###
      # Selkies parameters, for additional configurations see `selkies-gstreamer --help`
      ###
      # Change `SELKIES_ENCODER` to `x264enc`, `vp8enc`, or `vp9enc` if using software fallback without allocated GPUs or your GPU does not support `H.264 (AVCHD)` under the `NVENC - Encoding` section in https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new
      - SELKIES_ENCODER=x264enc
      - SELKIES_ENABLE_RESIZE=false
      # Initial video bitrate in kilobits per second, may be changed later within web interface
      - SELKIES_VIDEO_BITRATE=8000
      # Initial frames per second, may be changed later within web interface
      - SELKIES_FRAMERATE=60
      # Initial audio bitrate in bits per second, may be changed later within web interface
      - SELKIES_AUDIO_BITRATE=128000
      # Uncomment if network conditions rapidly fluctuate
      #    - SELKIES_CONGESTION_CONTROL=true
      # Enable Basic Authentication from the web interface
      - SELKIES_ENABLE_BASIC_AUTH=true
      # Defaults to `PASSWD` if unspecified
      #    - SELKIES_BASIC_AUTH_PASSWORD=mypasswd
      # Enable HTTPS web interface from inside the container
      - SELKIES_ENABLE_HTTPS=false
      # TURN server configuration
      - SELKIES_TURN_HOST=turn.warplay.cloud
      - SELKIES_TURN_PORT=3478
      - SELKIES_TURN_PROTOCOL=udp
      - SELKIES_TURN_TLS=false
      - SELKIES_TURN_USERNAME=some_user
      - SELKIES_TURN_PASSWORD=some_password
    # Volume mount trusted HTTPS certificate to new path for no web browser warnings
#    - SELKIES_HTTPS_CERT=/etc/ssl/certs/ssl-cert-snakeoil.pem
#    - SELKIES_HTTPS_KEY=/etc/ssl/private/ssl-cert-snakeoil.key
